# Generated by Django 5.0.6 on 2024-05-30 01:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewHistory",
            fields=[
                ("view_id", models.AutoField(primary_key=True, serialize=False)),
                ("view_date", models.DateField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ViewScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watch_score", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_mbti",
                    models.CharField(
                        choices=[
                            ("ESFP", "ESFP"),
                            ("ESFJ", "ESFJ"),
                            ("ESTP", "ESTP"),
                            ("ESTJ", "ESTJ"),
                            ("ENFP", "ENFP"),
                            ("ENFJ", "ENFJ"),
                            ("ENTP", "ENTP"),
                            ("ENTJ", "ENTJ"),
                            ("ISFP", "ISFP"),
                            ("ISFJ", "ISFJ"),
                            ("ISTP", "ISTP"),
                            ("ISTJ", "ISTJ"),
                            ("INFP", "INFP"),
                            ("INFJ", "INFJ"),
                            ("INTP", "INTP"),
                            ("INTJ", "INTJ"),
                        ],
                        max_length=4,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("남성", "남성"), ("여성", "여성")], max_length=2
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="user_app_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="user_app_permissions", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="VideoWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(help_text="Watch duration in seconds"),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user_app.user"
                    ),
                ),
            ],
        ),
    ]
